version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: tasklist
    networks:
      - app-network
    depends_on:
      - db
      - minio
    ports:
      - '8080:8080'

  db:
    image: postgres/postgres:latest
    container_name: postgres
    networks:
      - app-network
    environment:
      - POSTGRES_USER=jdbc:postgresql://localhost:5432/recipes_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=1234

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - app-network
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio
