spring:
  application:
  name: recipesServerApplication

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipes_db
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

spoonacular:
  url: https://api.spoonacular.com
  api-key: eaea88e64ac24145ac40bd513a3e3084
  scheme: apiKeyScheme