spring:
  application:
  name: recipesServerApplication

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://147.45.151.147:5432/default_db
    username: gen_user
    password: iL~\=1P0/!Ktnj

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

spoonacular:
  url: https://api.spoonacular.com
  api-key: e0360decfa3c48d1a5a1805e2565bd8b

minio:
  bucket: images
  url: http://92.255.76.152:9000
  accessKey: minioadmin
  secretKey: minioadmin